# 13th June 2026

# Machine Learning

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df = pd.read_csv(r"C:\Users\barat\Downloads\quikr_car.csv")
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

Steps for Data Cleaning and Preprocessing:
Finding Null Values
Dealing with Null Values
Finding Outliers
Label Encoding
Correct data types

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [15]:
df.dropna(inplace=True)
df = pd.get_dummies(df, columns=['fuel_type'],dtype='int', drop_first=True)
df

,name,company,year,Price,kms_driven,fuel_type_LPG,fuel_type_Petrol
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",0,1
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,0,0
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",0,1
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",0,1
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",0,0
...,...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",0,1
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",0,0
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",0,1
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",0,0
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",0,0

In [26]:
df['kms_driven'] = pd.to_numeric(df['kms_driven'].replace({'kms': '', ' ': '',",": ""}, regex=True))
df['Price'] = pd.to_numeric(df['Price'].replace({'Ask For Price': '', ' ': '',",": ""}, regex=True))
df.dropna(inplace=True)
df

,name,company,year,Price,kms_driven,fuel_type_LPG,fuel_type_Petrol
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,0,1
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,0,0
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,0,1
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,0,0
6,Ford Figo,Ford,2012,175000.0,41000,0,0
...,...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,0,1
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,0,0
886,Toyota Corolla Altis,Toyota,2009,300000.0,132000,0,1
888,Tata Zest XM Diesel,Tata,2018,260000.0,27000,0,0
889,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,0,0