# 4th July 2026

In [1]:
import seaborn as sns

df = sns.load_dataset("titanic")
df['survived'].value_counts(normalize=True)

survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [6]:
%pip install imbalanced-learn

Collecting imbalanced-learn
  Using cached imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (2.4.6)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn)
  Using cached sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (from imbalanced-learn) (3.6.0)
Using cached imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Using cached sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.2 sklearn-compat-0.1.6
Note: you may need to restart the kernel to use updated packages.

In [4]:
from imblearn.over_sampling import RandomOverSampler
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")
df.drop(['class','embark_town','deck','alive'], axis=1, inplace=True)

df.dropna(inplace=True)
df=pd.get_dummies(df,columns=['sex','embarked','who','adult_male','alone'],dtype='int',drop_first=True)
X=df.drop('survived',axis=1)
y=df['survived']

In [8]:
sampler = RandomOverSampler()
new_x,new_y= sampler.fit_resample(X,y)
len(X),len(new_x)

(712, 848)

In [9]:
new_y.value_counts()

survived
0    424
1    424
Name: count, dtype: int64

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import matplotlib.pyplot as plt
X=df.drop('survived',axis=1)
y=df['survived']
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

models = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier()
]

for model in models:

    model.fit(x_train, y_train)

    train_predictions = model.predict(x_train)
    test_predictions = model.predict(x_test)

    print("-" * 60)
    print(model.__class__.__name__)
    print("-" * 60)

    print(f"Train Accuracy : {accuracy_score(y_train, train_predictions):.4f}")
    print(f"Test Accuracy  : {accuracy_score(y_test, test_predictions):.4f}")

    print(f"Train Precision: {precision_score(y_train, train_predictions):.4f}")
    print(f"Test Precision : {precision_score(y_test, test_predictions):.4f}")

    print(f"Train Recall   : {recall_score(y_train, train_predictions):.4f}")
    print(f"Test Recall    : {recall_score(y_test, test_predictions):.4f}")

    print(f"Train F1 Score : {f1_score(y_train, train_predictions):.4f}")
    print(f"Test F1 Score  : {f1_score(y_test, test_predictions):.4f}")

------------------------------------------------------------
DecisionTreeClassifier
------------------------------------------------------------
Train Accuracy : 0.9877
Test Accuracy  : 0.7063
Train Precision: 1.0000
Test Precision : 0.6909
Train Recall   : 0.9689
Test Recall    : 0.6032
Train F1 Score : 0.9842
Test F1 Score  : 0.6441
------------------------------------------------------------
RandomForestClassifier
------------------------------------------------------------
Train Accuracy : 0.9877
Test Accuracy  : 0.7552
Train Precision: 0.9910
Test Precision : 0.7333
Train Recall   : 0.9778
Test Recall    : 0.6984
Train F1 Score : 0.9843
Test F1 Score  : 0.7154
------------------------------------------------------------
GradientBoostingClassifier
------------------------------------------------------------
Train Accuracy : 0.9262
Test Accuracy  : 0.7622
Train Precision: 0.9552
Test Precision : 0.7843
Train Recall   : 0.8533
Test Recall    : 0.6349
Train F1 Score : 0.9014
Test F1 Score  : 0.7018

In [13]:
data = pd.read_csv(r"C:\Users\barat\Downloads\Diabetes_prediction.csv")
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis
0,2,115.863387,56.410731,24.336736,94.385783,26.455940,0.272682,20.100494,0
1,2,92.490122,70.615520,23.443591,138.652426,23.910167,0.665160,44.912281,0
2,1,88.141469,63.262618,23.404364,149.358082,21.948250,0.676022,48.247873,1
3,2,108.453101,67.793632,20.751580,108.751638,24.209304,0.289636,42.749868,0
4,1,127.849443,94.725685,22.603078,25.269987,32.997477,0.601315,32.797789,0
...,...,...,...,...,...,...,...,...,...
995,1,103.496355,41.059401,24.930299,43.675978,25.846062,0.455884,19.905419,0
996,1,60.714150,64.082842,24.689064,111.562745,19.464280,0.250560,44.421874,1
997,0,97.597727,64.122312,22.140339,108.138552,22.733052,0.761463,58.949800,1
998,0,66.775137,55.908797,24.885274,219.521484,31.819187,0.382877,46.928923,0
999,0,87.647268,69.111593,25.621266,134.335745,31.098746,0.605828,41.785889,1

In [16]:
data.dropna(inplace=True)
data.columns = data.columns.str.lower().str.replace(" ", "_")
data

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,diagnosis
0,2,115.863387,56.410731,24.336736,94.385783,26.455940,0.272682,20.100494,0
1,2,92.490122,70.615520,23.443591,138.652426,23.910167,0.665160,44.912281,0
2,1,88.141469,63.262618,23.404364,149.358082,21.948250,0.676022,48.247873,1
3,2,108.453101,67.793632,20.751580,108.751638,24.209304,0.289636,42.749868,0
4,1,127.849443,94.725685,22.603078,25.269987,32.997477,0.601315,32.797789,0
...,...,...,...,...,...,...,...,...,...
995,1,103.496355,41.059401,24.930299,43.675978,25.846062,0.455884,19.905419,0
996,1,60.714150,64.082842,24.689064,111.562745,19.464280,0.250560,44.421874,1
997,0,97.597727,64.122312,22.140339,108.138552,22.733052,0.761463,58.949800,1
998,0,66.775137,55.908797,24.885274,219.521484,31.819187,0.382877,46.928923,0
999,0,87.647268,69.111593,25.621266,134.335745,31.098746,0.605828,41.785889,1

In [18]:
X=data.drop('diagnosis',axis=1)
y=data['diagnosis']
sampler = RandomOverSampler()
new_x,new_y= sampler.fit_resample(X,y)
len(X),len(new_x)

(1000, 1388)

In [19]:
new_y.value_counts()

diagnosis
0    694
1    694
Name: count, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

models = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    KNeighborsClassifier()
]

for model in models:

    model.fit(x_train, y_train)

    train_predictions = model.predict(x_train)
    test_predictions = model.predict(x_test)

    print("-" * 60)
    print(model.__class__.__name__)
    print("-" * 60)

    print(f"Train Accuracy : {accuracy_score(y_train, train_predictions):.4f}")
    print(f"Test Accuracy  : {accuracy_score(y_test, test_predictions):.4f}")

    print(f"Train Precision: {precision_score(y_train, train_predictions):.4f}")
    print(f"Test Precision : {precision_score(y_test, test_predictions):.4f}")

    print(f"Train Recall   : {recall_score(y_train, train_predictions):.4f}")
    print(f"Test Recall    : {recall_score(y_test, test_predictions):.4f}")

    print(f"Train F1 Score : {f1_score(y_train, train_predictions):.4f}")
    print(f"Test F1 Score  : {f1_score(y_test, test_predictions):.4f}")

------------------------------------------------------------
DecisionTreeClassifier
------------------------------------------------------------
Train Accuracy : 1.0000
Test Accuracy  : 0.5250
Train Precision: 1.0000
Test Precision : 0.2500
Train Recall   : 1.0000
Test Recall    : 0.2540
Train F1 Score : 1.0000
Test F1 Score  : 0.2520
------------------------------------------------------------
RandomForestClassifier
------------------------------------------------------------
Train Accuracy : 1.0000
Test Accuracy  : 0.6450
Train Precision: 1.0000
Test Precision : 0.1000
Train Recall   : 1.0000
Test Recall    : 0.0159
Train F1 Score : 1.0000
Test F1 Score  : 0.0274
------------------------------------------------------------
GradientBoostingClassifier
------------------------------------------------------------
Train Accuracy : 0.8387
Test Accuracy  : 0.6150
Train Precision: 0.9914
Test Precision : 0.2500
Train Recall   : 0.4733
Test Recall    : 0.1111
Train F1 Score : 0.6407
Test F1 Score  : 0.1538
------------------------------------------------------------
LogisticRegression
------------------------------------------------------------
Train Accuracy : 0.6975
Test Accuracy  : 0.6850
Train Precision: 0.6667
Test Precision : 0.0000
Train Recall   : 0.0082
Test Recall    : 0.0000
Train F1 Score : 0.0163
Test F1 Score  : 0.0000
------------------------------------------------------------
KNeighborsClassifier
------------------------------------------------------------
Train Accuracy : 0.7350
Test Accuracy  : 0.6600
Train Precision: 0.6240
Test Precision : 0.4194
Train Recall   : 0.3210
Test Recall    : 0.2063
Train F1 Score : 0.4239
Test F1 Score  : 0.2766

c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [21]:
from imblearn.over_sampling import SMOTE
data = pd.read_csv(r"C:\Users\barat\Downloads\Diabetes_prediction.csv")
data.dropna(inplace=True)
data.columns = data.columns.str.lower().str.replace(" ", "_")
X=data.drop('diagnosis',axis=1)
y=data['diagnosis']
sampler = SMOTE()
new_x,new_y= sampler.fit_resample(X,y)

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

models = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    KNeighborsClassifier()
]

for model in models:

    model.fit(x_train, y_train)

    train_predictions = model.predict(x_train)
    test_predictions = model.predict(x_test)

    print("-" * 60)
    print(model.__class__.__name__)
    print("-" * 60)

    print(f"Train Accuracy : {accuracy_score(y_train, train_predictions):.4f}")
    print(f"Test Accuracy  : {accuracy_score(y_test, test_predictions):.4f}")

    print(f"Train Precision: {precision_score(y_train, train_predictions):.4f}")
    print(f"Test Precision : {precision_score(y_test, test_predictions):.4f}")

    print(f"Train Recall   : {recall_score(y_train, train_predictions):.4f}")
    print(f"Test Recall    : {recall_score(y_test, test_predictions):.4f}")

    print(f"Train F1 Score : {f1_score(y_train, train_predictions):.4f}")
    print(f"Test F1 Score  : {f1_score(y_test, test_predictions):.4f}")

------------------------------------------------------------
DecisionTreeClassifier
------------------------------------------------------------
Train Accuracy : 1.0000
Test Accuracy  : 0.5500
Train Precision: 1.0000
Test Precision : 0.2923
Train Recall   : 1.0000
Test Recall    : 0.3016
Train F1 Score : 1.0000
Test F1 Score  : 0.2969
------------------------------------------------------------
RandomForestClassifier
------------------------------------------------------------
Train Accuracy : 1.0000
Test Accuracy  : 0.6600
Train Precision: 1.0000
Test Precision : 0.2727
Train Recall   : 1.0000
Test Recall    : 0.0476
Train F1 Score : 1.0000
Test F1 Score  : 0.0811
------------------------------------------------------------
GradientBoostingClassifier
------------------------------------------------------------
Train Accuracy : 0.8400
Test Accuracy  : 0.6400
Train Precision: 1.0000
Test Precision : 0.3333
Train Recall   : 0.4733
Test Recall    : 0.1429
Train F1 Score : 0.6425
Test F1 Score  : 0.2000
------------------------------------------------------------
LogisticRegression
------------------------------------------------------------
Train Accuracy : 0.6975
Test Accuracy  : 0.6850
Train Precision: 0.6667
Test Precision : 0.0000
Train Recall   : 0.0082
Test Recall    : 0.0000
Train F1 Score : 0.0163
Test F1 Score  : 0.0000
------------------------------------------------------------
KNeighborsClassifier
------------------------------------------------------------
Train Accuracy : 0.7350
Test Accuracy  : 0.6600
Train Precision: 0.6240
Test Precision : 0.4194
Train Recall   : 0.3210
Test Recall    : 0.2063
Train F1 Score : 0.4239
Test F1 Score  : 0.2766

c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])